### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by Tannerghosen** [Tannerghosen/Skeleton#1]
- [x] Fix the status saying 'undefined servers' - Low priority
- [x] Fix any v11-to-v12 issues - High priority
- [x] 'Fix' a possible issue where the bot stops properly responding to updated prefixes - High priority
- [x] The ping's command API Latency no longer works. See if that's because of discord.js v12 removing it (no seriously, I genuinely don't know) or we fucked up something along the way. - Low Priority,
- [x] Add more funny quotes for Skeletor, Yoda, and perhaps more characters. - Low Priority
- [x] Think of new fun games you could program. - Mid Priority

**Comment by TANMAN-TANNER** [comment]
Status fixed. As for the issue where bots don't respond properly, it seems deleting the sqllite files it hosted itself on fixed the issue and it repopulated. Might of been cut ~~midflow~~ mid process and it didn't save shit properly. I'll keep an eye on it to see if there's any more issues, but for now I'll call both of these issues on the to-do list 'closed'.

**Comment by TANMAN-TANNER** [comment]
Fixed API Latency showing as NaN. Changed client.ping to client.ws.ping, which seems to fixed it.

**Comment by Tannerghosen** [comment]
Last 2 issues are no longer a concern. Closing issue.
