### ISSUE TITLE
To-do List for Version 6

### ISSUE THREAD

**Issue by Tannerghosen** [Tannerghosen/Skeleton#1]
- [x] Fix a bug with config, in which an input that's blank could be registered as a valid response. - Very High Priority
- [ ] Add fun, new commands or features. - Mid Priority
- [ ] Add new 8-Ball lines, make sure it balances out between 2 yes's, 1 no, and 1 non-committal responses. - Mid Priority
- [x] Update RPS command to be a bit more pleasing to the eyes, i.e. not a bunch of repeated strings. - Mid Priority, would be nice to have before Version 5.
- [x] Judge if we really should delete server settings when the bot leaves a server. Is it a common practice? - Low Priority
- [x] Review grammar for some of the commands. - Low Priority

**Comment by Tannerghosen** [comment]
New commands are now a high priority due to the removal of dice.

**Comment by Tannerghosen** [comment]
* (This is high priority as it's using older code still, which while at the moment isn't a big issue, it'd be nice to fix all these issues up. )

**Comment by Tannerghosen** [comment]
Issue 1 resolved in https://github.com/Tannerghosen/Skeleton/releases/tag/5.667
